### ISSUE TITLE
Failed setup

### ISSUE THREAD

**Issue by LassPar** [ryanbdclark/owlet#1]
Hi. After I configured region, username and password, i get this message.

![Screenshot_2023-07-11-02-02-21-95_c3a231c25ed346e59462e84656a70e50](https://github.com/ryanbdclark/owlet/assets/30269547/b143dc27-8517-442b-91b9-7032290d8e1c)

Username and password are correct.

**Comment by ryanbdclark** [comment]
Thanks for raising this.

Do you know what version of sock you have? My guess is that it's a v2 sock that is connected to your account, currently only the V3 sock (and dream sock) are supported. If you do have a V2 sock and would be happy to provide your JSON responses from the api then I'd be happy to add support for the V2 sock.

Let me know if you need any help with any of the above.

**Comment by ryanbdclark** [comment]
Closing as no response for 1 month

**Comment by Cyberbob241** [comment]
Hi, I have the same problem like @LassPar 

I got the following log message 


----------------------------------
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.owlet.coordinator
Source: helpers/update_coordinator.py:290
Integration: Owlet Smart Sock
First occurred: 20:35:37 (3 occurrences)
Last logged: 20:36:00

Unexpected error fetching owlet data: 'LOST_POWER_ALRT'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/owlet/coordinator.py", line 44, in _async_update_data
    properties = await self.sock.update_properties()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyowletapi/sock.py", line 242, in update_properties
    self._properties = await self.normalise_properties()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyowletapi/sock.py", line 180, in normalise_properties
    properties = {
                 ^
  File "/usr/local/lib/python3.11/site-packages/pyowletapi/sock.py", line 181, in <dictcomp>
    key: type(self._raw_properties[property]["value"])
              ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'LOST_POWER_ALRT'


--------------------------------

Do you know this kind of problem? 

We use the socks and both are v3 accordingly to the packing. 

Thanks!
