### ISSUE TITLE
5 min sensor update interval

### ISSUE THREAD

**Issue by LassPar** [ryanbdclark/owlet#10]
Hi. On Decenber, I have noticed, that all sensors update interval is about 5 min. Before all sensors updated correctly (from June to November). I wonder if it is somethong wrong with integration or owlet istelf.

![IMG_20231224_224444](https://github.com/ryanbdclark/owlet/assets/30269547/6886a8d7-f2d6-48ae-98c0-da48023be2fa)

![IMG_20231224_224420](https://github.com/ryanbdclark/owlet/assets/30269547/815a47ef-372e-45d5-9160-32d85c60fb30)

**Comment by ryanbdclark** [comment]
Couple of things that you could check if possible. There is the option to adjust the scan interval within the integration. The default is 5 seconds has this been changed on your system by accident perhaps? You can check as per the below screenshots. 

![image](https://github.com/ryanbdclark/owlet/assets/42173121/55eef744-cdc8-4945-a687-4159e6c16c50)

![image](https://github.com/ryanbdclark/owlet/assets/42173121/2058a989-9c88-4a10-8ce0-533b7dd57802)


If that’s still set at 5 seconds could you try to remove and reinstall the integration and see if the issue persists?

If the issue persists are there any errors in the home assistant logs relating to the owlet integration?

Failing that if you check the owlet app itself are the stats within the owlet app updating every 5 seconds as you’d expect?

**Comment by LassPar** [comment]
I don't use app anymore, because HA integration is much better. I checked the app and is says "base disconnected". So my problem is owlet-end. Reboot doesnt work. I will try to reinstall base and sock and report if it works...
![Screenshot_2023-12-30-00-22-00-00_09dae6d9eb2c69038d0d989d33d6beb9](https://github.com/ryanbdclark/owlet/assets/30269547/3b33f37f-b6bf-4cee-a0b2-247f00500c34)

**Comment by LassPar** [comment]
I don't use app anymore, because HA integration is much better. I checked the app and is says "base disconnected". So my problem is owlet-end. Reboot doesnt work. I will try to reinstall base and sock and report if it works...
![IMG_20231230_002810](https://github.com/ryanbdclark/owlet/assets/30269547/ddbe0698-87d1-4215-b33e-9af638f85de8)

**Comment by ryanbdclark** [comment]
Closing
