### ISSUE TITLE
Scan interval minimum greater than default value

### ISSUE THREAD

**Issue by bherbruck** [ryanbdclark/owlet#11]
The scan interval has a default of 5 seconds but a minimum of 10 seconds in the UI configuration. It would be nice to have this at 1 second or even 0.5 if we don't risk getting rate-limited.

https://github.com/ryanbdclark/owlet/blob/main/custom_components/owlet/config_flow.py#L168

![image](https://github.com/ryanbdclark/owlet/assets/5258126/2afed5df-e907-41b6-862d-7d2a59ec41d5)

**Comment by seanford** [comment]
This is a bug.  I just used Chrome Dev tools to get it back to 5s.

**Comment by ryanbdclark** [comment]
This will be fixed in todays update
