### ISSUE TITLE
Problem adding a sock

### ISSUE THREAD

**Issue by compr00t** [ryanbdclark/owlet#13]
Upon adding a sock, I get the following error:

```
Logger: homeassistant.setup
Source: setup.py:377
First occurred: 23:22:22 (2 occurrences)
Last logged: 23:22:22

Unable to prepare setup for platform owlet.binary_sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
Unable to prepare setup for platform owlet.sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
```

**Comment by ryanbdclark** [comment]
What Owlet integration version are you using?
What homeassistant version are you using?

I think you might need to update homeassistant, DeviceInfo was moved to the device_registry around 7 months ago. I'm running newest homeassistant and Owlet version and this works fine

**Comment by compr00t** [comment]
@ryanbdclark you are absolutely right, so sorry about that. It seems, HA changed the name of their repo where I pull the docker image, so everytime I updated, I reinstalled 2023.06 without noticing… I now updated to the actual latest version and everything works like a charm now. Thanks so much for a great integration!

**Comment by ryanbdclark** [comment]
No problem :). Thanks for confirming.
