### ISSUE TITLE
Duplicate integration?

### ISSUE THREAD

**Issue by Intecpsp** [ryanbdclark/owlet#5]
How is this different from https://github.com/jlamendo/ha-sensor.owlet by @jlamendo?

**Comment by ryanbdclark** [comment]
The integration you linked doesn't use a separate API library, the API is baked into the integration itself. This is the first point in HA's development check list stating that all external communication should be wrapped in a separate library https://developers.home-assistant.io/docs/development_checklist.

The integration I created allows setup from the UI, reauth and allows to change options from UI. I believe my integration also exposes more sensors and conforms more to the standard structure of core HA integrations whereas the integration you linked has most of the code in one file.

Both have their place I'm sure. I created mine as a pet project and just added it to HACS as I believed other people would find it useful and easier to use that some of the other Owlet integrations I saw (including the one you linked)
