### ISSUE TITLE
Failed setup

### ISSUE THREAD

**Issue by Cyberbob241** [ryanbdclark/owlet#7]
Hi, I have the same problem like @LassPar

![image](https://github.com/ryanbdclark/owlet/assets/37499476/a24fa3d1-ae00-4513-9554-587b35058e27)

Do you know this kind of problem?
I saw a similar log message in one of the closed issues and this kind of problem should be fixed. 

We use two socks and both are v3 accordingly to the packing.

Thanks!

I got the following log message

--------

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.owlet.coordinator
Source: helpers/update_coordinator.py:290
Integration: Owlet Smart Sock
First occurred: 20:35:37 (3 occurrences)
Last logged: 20:36:00

Unexpected error fetching owlet data: 'LOST_POWER_ALRT'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/owlet/coordinator.py", line 44, in _async_update_data
properties = await self.sock.update_properties()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyowletapi/sock.py", line 242, in update_properties
self._properties = await self.normalise_properties()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyowletapi/sock.py", line 180, in normalise_properties
properties = {
^
File "/usr/local/lib/python3.11/site-packages/pyowletapi/sock.py", line 181, in
key: type(self._raw_properties[property]["value"])
~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'LOST_POWER_ALRT'

**Comment by ryanbdclark** [comment]
I'll have a look today about catching these errors so the setup won't fail. I'll do this for all fields rather than the one you've specified as different revisions of the sock appear to all have different properties

**Comment by ryanbdclark** [comment]
I've amended my API calling library to ignore any properties that don't exist on the response. I haven't had a chance today to then make the subsequent changes to the integration but will do as soon as I can and push out an update.

**Comment by Cyberbob241** [comment]
Thanks for the quick response. I'm looking forward to test the update.

**Comment by ryanbdclark** [comment]
I've now released version 2023.11.1 which should fix this. Any properties that don't exist for a specific sock version are now just ignored rather than throwing an error. I tested as much as I could although more difficult for me to test as my sock version has all the properties that the integration exposes.

**Comment by Cyberbob241** [comment]
I updated the integration and getting all values now. 
Thank you again for your help!

**Comment by ryanbdclark** [comment]
Thanks for confirming
