### ISSUE TITLE
Base off state

### ISSUE THREAD

**Issue by papadi** [ryanbdclark/owlet#9]
When the base is off it is not reflected anywhere on the integration and the collected data aren't even cleared. Even the last update values change even though the data is obviously stale.

Thx for this integration, btw.

**Comment by yuejon** [comment]
Agree that it would be helpful to have the base station status. I used to use the other [integration](https://github.com/jlamendo/ha-sensor.owlet) which has the base station information in an attribute, so it would seem that it is available. I switched to this integration because it had more sensors available (like skin temperature).

Would be awesome if we could turn the base station on and off from the integration itself.

Thanks.

**Comment by ryanbdclark** [comment]
There are a couple of issues with this request. All this integration is doing is pulling the raw data from the Owlet api and presenting it in Home Assistant. The API provides no real way of knowing when the base station is off from what I can tell. The "bso" (base station on flag) is 0 when the sock is charging and 1 when the sock is in use. If you were to unplug the base when the sock is in use the "bso" flag would stay at 1 indicating the base station is on when it's not. This is just how the API works unfortunately.

Similarly when the base station is off the owlet api does not clear the vitals data. So when homeassistant calls the api it rightly changes the last updated time (the api calls are still successful) and sets the vital data to the data received from the api (the last vitals data from the sock before the base station lost power). From what I've seen in testing there is no clear indicator showing that the base is off or has lost power. I'll happily provide the "bso" flag from the API as a binary sensor but not sure what information that will give you other than telling you if that sock is in use or not.

The bso flag will be exposed in the next update which will be today.

**Comment by gabriel403** [comment]
@ryanbdclark I don't suppose the API allows you to turn the base station off/on? When I'm rocking my 6 month old to sleep in our rocking chair I have to turn the base station off otherwise it incorrectly triggers an alert, would be great if we could do it in ha
